
runtime: python27
api_version: 1
threadsafe: yes

handlers:      

- url: /.*
  script: main.app
  secure: always


libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: latest



